### ISSUE TITLE
Version 0.0.4 doesn't include seeding bug

### ISSUE THREAD

**Issue by meltedice** [jffjs/mongoid_auto_inc#2]
Hi,

Thank you for providing useful gem.

I encountered a seeding bug with mongoid_auto_inc 0.0.4.
(Installed by "gem install mongoid_auto_inc")
So I forked and tried to fix it, but It already fixed.
On master branch HEAD, the bug is already fixed, but it's not applied to rubygems.org.

Could you please increment mongoid_auto_inc version and push to rubygems.ors?

best regards, ice

**Comment by jffjs** [comment]
Hi ice,

I've updated rubygems to include the latest version.  Hope this helps!

**Comment by meltedice** [comment]
Hi jffjs,

Thank you very much.
It works!
