### ISSUE TITLE
undefined method `auto_increment'

### ISSUE THREAD

**Issue by ktkaushik** [jffjs/mongoid_auto_inc#6]
This is my Model using Mongoid

```
class Client
  include Mongoid::Document
  include Mongoid::Paranoia

  field :name, :type => String
  field :email, :type => String
  field :phone_no, :type => String
  field :address, :type => String
  field :contact_person, :type => String
  auto_increment :phone_no
end
```

And i keep getting this error
`undefined method `auto_increment' for Client:Class`

Am i missing something here ?

**Comment by jffjs** [comment]
Did you run `bundle install` after adding this gem to your Gemfile?

Also, this is unrelated, but I think you might not be using this gem correctly based on the model you listed there.  The `auto_increment` method will automatically create the the `field` that it specifies, you don't have to create the field prior to calling `auto_increment`.  So in your example there, it will automatically create  `phone_no` as an `Integer` field, which is going to overwrite the `field :phone_no, :type => String` line that you already have there.

**Comment by ktkaushik** [comment]
That does it. Thanks.
